steps:
# build the container images
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/gke-react:${_INCREMENT_1}", "./app/"]
  # push the container image to gcloud registry
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/gke-react:${_INCREMENT_1}"]

substitutions:
    _INCREMENT_1: 1.0 # default value
#- name: 'gcr.io/cloud-builders/kubectl'
#  args:
#  - 'apply'
#  - '-f'
#  - 'app/kubeconfig.yaml'
#  env:
#  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
#  - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'
