steps:
# build the container images
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/gke-react:$SHORT_SHA", "./app/"]
  # push the container image to gcloud registry
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/gke-react:$SHORT_SHA"]

#substitutions::
#    _INCREMENT_1: $TAG_NAME # default valuem
#- name: 'gcr.io/cloud-builders/kubectl'
#  args:
#  - 'apply'
#  - '-f'
#  - 'app/kubeconfig.yaml'
#  env:
#  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
#  - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'
