steps:
- name: 'gcr.io/cloud-builders/gsutil'
  id: copy_config
  waitFor: ['-']
  args: ['rsync', 'gs://${_CONFIG_BUCKET}/', '/config']
  volumes:
  - name: 'config'
    path: '/config'

- name: 'gcr.io/$PROJECT_ID/buildnum'
  id: setup_env
  args: ['/config/buildnum', '.buildenv']
  waitFor: ['copy_config']
  volumes:
  - name: 'config'
    path: '/config'

- name: 'gcr.io/cloud-builders/gsutil'
  id: save_config
  args: ['cp', '/config/buildnum', 'gs://${_CONFIG_BUCKET}/buildnum']
  waitFor: ['setup_env']
  volumes:
  - name: 'config'
    path: '/config'

# build the container images
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/gke-react", "./app/"]
  # push the container image to gcloud registry
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/gke-react"]

#- name: 'gcr.io/cloud-builders/kubectl'
#  args:
#  - 'apply'
#  - '-f'
#  - 'app/kubeconfig.yaml'
#  env:
#  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
#  - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'
