steps:
#- name: node
#  entrypoint: yarn
#  args: [ 'install' ]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy","app/app.yaml"]
  timeout: 2000s

timeout: 2000s

#images:
#- 'gcr.io/$PROJECT_ID/myreact-image'
